CREATE TABLE marcas (
 id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 marca VARCHAR(255)                            NOT NULL,

 CONSTRAINT pk_marca            PRIMARY KEY (id),
 CONSTRAINT uc_marca_nome       UNIQUE (marca)
);

CREATE TABLE carros (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ano        INT                             NOT NULL,
    cor        VARCHAR(255)                    NOT NULL,
    nome       VARCHAR(255)                    NOT NULL,
    modelo     VARCHAR(255)                    NOT NULL,
    km         INT                             NOT NULL DEFAULT 0,
    tipo       VARCHAR(255)                    NOT NULL,
    marca_id   BIGINT                          NOT NULL,
    reservado  BOOLEAN                         NOT NULL,
    disabled   BOOLEAN                         NOT NULL,
    url_imagem VARCHAR(255),
    preco      DOUBLE PRECISION                NOT NULL,

   CONSTRAINT pk_carro             PRIMARY KEY (id),
   CONSTRAINT fk_carro_on_marca FOREIGN KEY (marca_id) REFERENCES marcas (id)
);

CREATE TABLE usuarios (
 id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 login VARCHAR(255)                            NOT NULL,
 senha VARCHAR(255)                            NOT NULL,
 role  VARCHAR(60)                             NOT NULL  CHECK (role IN ('ROLE_ADMIN', 'ROLE_USER')),

 CONSTRAINT pk_usuario             PRIMARY KEY (id),
 CONSTRAINT uc_usuario_login       UNIQUE (login)
);

-- INSERT (USUARIO - ADMIN)
INSERT INTO usuarios (login, senha, role) VALUES ('admin', '$2a$10$RaHBqPLd5WvGoslX1DNGNOIXdVqzEyUEuqnlL7rrKJ6DDv59HPaYa', 'ROLE_ADMIN');

-- Marcas
 INSERT INTO marcas (marca) VALUES
  ('Audi'),  ('Nissan'),    ('Bmw'),
  ('Chery'), ('Chevrolet'), ('Citroen'),
  ('Dodge');

-- Carros
INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('TWINPOWER M40I', 368.999, false, 0,
'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTw4H-TFnjLF902lWhsHaQesak81kWlOKcntA&usqp=CAU',
2022, 'PRETO', 'SUV',false, 3, 'A3');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo)
VALUES ('TURBO SPORT', 289.299, false, 0,
'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQlV8QGvupdEuJMVMTS_TbH8BE5PfFWrqHv6TgkoKFubB58edxs4rtySZjZk6PJm4oJBd4&usqp=CAU',
2022, 'BRANCO', 'SEDAN',false, 3, '330i');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo)
VALUES ('30D I6 TURBO', 273.999, false, 87922, 'https://s3.ecompletocarros.dev/images/lojas/164/veiculos/55708/veiculoInfoVeiculoImagesMobile/vehicle_image_1616440312_63c85d8fea3a65f4a0888e30607c53a7.jpeg',
2020, 'BRANCO', 'SUV',false, 3, 'X5');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('TFSI SPORTBACK PRESTIGE', 255.999, true, 16707, 'https://image.webmotors.com.br/_fotos/AnuncioUsados/gigante/2021/202112/20211206/audi-a5-2.0-tfsi-gasolina-sportback-prestige-plus-s-tronic-WMIMAGEM06504580777.jpg',
2019, 'PRATA', 'SEDAN',false, 1, 'A5');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('M COUPE V8 BI-TURBO', 234.999, false, 73800, 'https://s3.ecompletocarros.dev/images/lojas/164/veiculos/12732/veiculoInfoVeiculoImagesMobile/vehicle_image_1581130652_4c7da5d1a826bc1173e35191cd691661.jpeg',
2015, 'AZUL', 'SUV',false, 3, 'X6');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('TURBO LE CD', 232.999, false, 16808, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5pH3wK7_qgQv8lxRFEP80mLF2SmZ94iJSGw&usqp=CAU',
2018, 'AZUL', 'PICKUP',false, 2, 'Frontier');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('2500 LAMARINE', 224.775, false, 87500, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMHc7010XO_adKjQ9z5kMmmKgoQWmFrLXxPw&usqp=CAU',
2018, 'PRETO', 'PICKUP', false, 7, 'Ram');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo,  disabled,marca_id, modelo) VALUES
('TFSI PRESTIGE PLUS', 214.799, false, 13899, 'https://http2.mlstatic.com/D_NQ_NP_647607-MLB48952079404_012022-O.jpg',
2021, 'PRATA', 'SEDAN', false, 1, 'A4');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('SL X-GEAR', 51000, true, 1231, 'https://www.chavesnamao.com.br/carros/rj/nissan-livina-1.8-sl-x-gear-16v-4p/',
2022, 'BRANCO', 'SUV', false, 3, 'A3');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('START SV', 32.599, false, 1811, 'https://images.kavak.services/images/150943/EXTERIOR-frontSidePilotNear-1639853667843.jpeg?d=540x310',
2022, 'PRATA', 'SEDAN', false, 3, 'A3');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('SV', 97.989, false, 0, 'https://i0.statig.com.br/bancodeimagens/1a/66/k0/1a66k0oj9wbtss3ddkynj9i3b.jpg', 2018,
'MARROM', 'SEDAN', false, 3, 'A3');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('LOUNGE MPFI TENDENCE', 100.299, false, 0, 'https://image.webmotors.com.br/_fotos/AnuncioUsados/gigante/2022/202205/20220519/CITROEN-C4-LOUNGE-2.0-MPFI-TENDANCE-16V-FLEX-4P-MANUAL-wmimagem15414687621.jpg',
2021, 'BRANCO', 'SEDAN', false, 6, 'Q3');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('GLX', 130.999, false, 9181, 'https://motortudo.com/wp-content/uploads/2021/11/golf-azul-carros-esportivos-antigos-3.jpeg',
2021, 'AZUL', 'SUV', false, 6, 'Aircross');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('RT AWD V6', 65.999, false, 0, 'https://s3-sa-east-1.amazonaws.com/revresources/palhano-veiculos/imagens_veiculos/640_480_dodge-journey-rt-3-6-v6-awd-13-13-4-2.jpg',
2022, 'CINZA', 'SUV', false, 7, 'Journey');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('START SV', 73.999, false, 18191, 'https://images.kavak.services/images/128330/EXTERIOR-frontSidePilotNear-16358551762481.jpg?d=540x310',
2019, 'BRANCO', 'SEDAN', false, 2, 'A3');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('MPFI JOY', 58.099, false, 23012, 'https://http2.mlstatic.com/D_NQ_NP_925693-MLB48642669487_122021-O.jpg',
2017, 'PRATA', 'HATCHBACK', true, 5, 'Onix');

INSERT INTO carros (nome, preco, reservado, km, url_imagem, ano, cor, tipo, disabled, marca_id, modelo) VALUES
('MPFI ELEGANCE', 79.999, true, 12101, 'https://seminovosrj.com.br/fotos/348/681011/22.jpg',
2018, 'PRETO', 'SEDAN', true, 5, 'A5');